### ISSUE TITLE
Cannot scroll on react version

### ISSUE THREAD

**Issue by AirplaneA220** [juaneth/Omnipetal#5]
While using the react version I noticed that I could not scroll down on the settings menu which in windowed mode is necessary to reach themes with default size of window.

https://user-images.githubusercontent.com/84548624/178196143-19553b0a-ca84-4665-819c-c2b70c67fa35.mp4

**Comment by AirplaneA220** [comment]
Note while i am on the settings menu I am trying to scroll, kinda hard to show on video (I would try it yourself to see it)

**Comment by juaneth** [comment]
So this is a current issue as the scrollbar wouldn't go over just the main content, it always appeared over the navbar so I tried to install a package for custom navbars and I tried it and it just didn't work for me so I uninstalled it but then also left body to hide overflow still, dw I've noticed it's already been fixed I just havent pushed in a while lmao

**Comment by AirplaneA220** [comment]
I would push that soon because it kinda makes it hard to get to all of the settings menu

**Comment by AirplaneA220** [comment]
I'll close this since you have a fix already
